server:
  port: 8081
spring:
  application:
    name: my-first-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka