
server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false